name: TypedAssistantBeta
version: "0.0.2"
ports:
  3822/tcp: 3822
  3823/tcp: 3823
slug: typed-assistant
init: false
description: Automate Home Assistant with TypeScript.
url: "https://github.com/TypedAssistant/TypedAssistantBeta"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - addons:rw
startup: services
hassio_role: manager
hassio_api: true
homeassistant_api: true
ingress: true
boot: auto
options:
  commandToRun: "bun src/index.tsx"
  hassToken: null
  hassUrl: "http://192.168.86.11:8123"
  githubToken: null
  githubUsername: null
  githubRepo: null
  githubBranch: "main"
schema:
  commandToRun: "str?"
  hassToken: "str?"
  hassUrl: "str?"
  githubToken: "str?"
  githubUsername: "str?"
  githubRepo: "str?"
  githubBranch: "str?"