name: Release

env:
  CI: true
  NPM_CONFIG_PROVENANCE: "true"

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: install npm
        run: npm i npm@11.18.0 -g
      - name: install pnpm
        run: npm i pnpm@10.7.1 -g
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint and test
        run: pnpm validate
      - name: version packages
        run: ./node_modules/.bin/changeset version
      - name: commit version changes
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Version packages [skip ci]"
          git push
      - name: publish packages
        run: ./node_modules/.bin/changeset publish
